---
- hosts: targets
  vars:
    provision: no
  tasks:
  - name: run the common role against all the targets
    include_role:
      name: common

- hosts: localhost
  tasks:
  - name: create a file to log the updates
    file:
      path: "/home/{{ansible_user}}/ansible_auto_updates"
      owner: "{{ansible_user}}"
      mode: 0700
      state: touch
  
  - name: append the date time to the auto update log
    shell: "echo ansible update start $( date +%s ) >> /home/{{ansible_user}}/ansible_executed"
    