---
- hosts: targets
  vars:
    provision: no
  tasks:
  - name: run the common role against all the targets
    include_role:
      name: common

- hosts: localhost
  tasks:
  - name: performing updates
    file:
      path: "/home/{{ansible_user}}/ansible_executed"
  
  - name:
    command: "echo $( date +%s ) >> /home/{{ansible_user}}/ansible_executed"
    