---
- name: configure crontab to pull the current repo daily
  cron:
    name: make sure the current system is upto date
    hour: "*"
    minute: "*"
    job: "echo 'ansible crontab was run' >> /home/{{ansible_user}}/crontab_exec"