---
- name: create the directory to store the cron job script
    file:
      path: "/home/{{ansible_user}}/ansible_auto_updates"
      owner: "{{ansible_user}}"
      mode: 0755
      state: directory
      
- name: add the script to which will be run as the crontab
  template:
    src: cron_job.j2
    dest: "/home/{{ansible_user}}/ansible_auto_updates/cron_job.sh"
    
- name: configure crontab to pull the current repo daily
  cron:
    name: make sure the current system is upto date
    hour: "*"
    minute: "*/2"
    job: "/home/{{ansible_user}}/ansible_auto_updates/cron_job.sh"